//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClientView.localhost {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Lab_091Soap", Namespace="http://tempuri.org/")]
    public partial class Lab_091 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllCountriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCountryByCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCityByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCitiesByCountryCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Lab_091() {
            this.Url = global::ClientView.Properties.Settings.Default.ClientView_localhost_Lab_091;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllCountriesCompletedEventHandler GetAllCountriesCompleted;
        
        /// <remarks/>
        public event GetCountryByCodeCompletedEventHandler GetCountryByCodeCompleted;
        
        /// <remarks/>
        public event GetCityByNameCompletedEventHandler GetCityByNameCompleted;
        
        /// <remarks/>
        public event GetAllCitiesByCountryCodeCompletedEventHandler GetAllCitiesByCountryCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCountries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Country[] GetAllCountries() {
            object[] results = this.Invoke("GetAllCountries", new object[0]);
            return ((Country[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCountriesAsync() {
            this.GetAllCountriesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCountriesAsync(object userState) {
            if ((this.GetAllCountriesOperationCompleted == null)) {
                this.GetAllCountriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCountriesOperationCompleted);
            }
            this.InvokeAsync("GetAllCountries", new object[0], this.GetAllCountriesOperationCompleted, userState);
        }
        
        private void OnGetAllCountriesOperationCompleted(object arg) {
            if ((this.GetAllCountriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCountriesCompleted(this, new GetAllCountriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCountryByCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Country GetCountryByCode(string code) {
            object[] results = this.Invoke("GetCountryByCode", new object[] {
                        code});
            return ((Country)(results[0]));
        }
        
        /// <remarks/>
        public void GetCountryByCodeAsync(string code) {
            this.GetCountryByCodeAsync(code, null);
        }
        
        /// <remarks/>
        public void GetCountryByCodeAsync(string code, object userState) {
            if ((this.GetCountryByCodeOperationCompleted == null)) {
                this.GetCountryByCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCountryByCodeOperationCompleted);
            }
            this.InvokeAsync("GetCountryByCode", new object[] {
                        code}, this.GetCountryByCodeOperationCompleted, userState);
        }
        
        private void OnGetCountryByCodeOperationCompleted(object arg) {
            if ((this.GetCountryByCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCountryByCodeCompleted(this, new GetCountryByCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCityByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public City GetCityByName(string name) {
            object[] results = this.Invoke("GetCityByName", new object[] {
                        name});
            return ((City)(results[0]));
        }
        
        /// <remarks/>
        public void GetCityByNameAsync(string name) {
            this.GetCityByNameAsync(name, null);
        }
        
        /// <remarks/>
        public void GetCityByNameAsync(string name, object userState) {
            if ((this.GetCityByNameOperationCompleted == null)) {
                this.GetCityByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCityByNameOperationCompleted);
            }
            this.InvokeAsync("GetCityByName", new object[] {
                        name}, this.GetCityByNameOperationCompleted, userState);
        }
        
        private void OnGetCityByNameOperationCompleted(object arg) {
            if ((this.GetCityByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCityByNameCompleted(this, new GetCityByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCitiesByCountryCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public City[] GetAllCitiesByCountryCode(string countryCode) {
            object[] results = this.Invoke("GetAllCitiesByCountryCode", new object[] {
                        countryCode});
            return ((City[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCitiesByCountryCodeAsync(string countryCode) {
            this.GetAllCitiesByCountryCodeAsync(countryCode, null);
        }
        
        /// <remarks/>
        public void GetAllCitiesByCountryCodeAsync(string countryCode, object userState) {
            if ((this.GetAllCitiesByCountryCodeOperationCompleted == null)) {
                this.GetAllCitiesByCountryCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCitiesByCountryCodeOperationCompleted);
            }
            this.InvokeAsync("GetAllCitiesByCountryCode", new object[] {
                        countryCode}, this.GetAllCitiesByCountryCodeOperationCompleted, userState);
        }
        
        private void OnGetAllCitiesByCountryCodeOperationCompleted(object arg) {
            if ((this.GetAllCitiesByCountryCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCitiesByCountryCodeCompleted(this, new GetAllCitiesByCountryCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Country {
        
        private string codeField;
        
        private string nameField;
        
        private string continentField;
        
        private string regionField;
        
        private int populationField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Continent {
            get {
                return this.continentField;
            }
            set {
                this.continentField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public int Population {
            get {
                return this.populationField;
            }
            set {
                this.populationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class City {
        
        private int idField;
        
        private string nameField;
        
        private string countryCodeField;
        
        private string districtField;
        
        private int populationField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public int Population {
            get {
                return this.populationField;
            }
            set {
                this.populationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetAllCountriesCompletedEventHandler(object sender, GetAllCountriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCountriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCountriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Country[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Country[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetCountryByCodeCompletedEventHandler(object sender, GetCountryByCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCountryByCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCountryByCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Country Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Country)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetCityByNameCompletedEventHandler(object sender, GetCityByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCityByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCityByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public City Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((City)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetAllCitiesByCountryCodeCompletedEventHandler(object sender, GetAllCitiesByCountryCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCitiesByCountryCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCitiesByCountryCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public City[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((City[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591